/** @type {import('typedoc').TypeDocOptions} */
module.exports = {
  tsconfig: "tsconfig.docs.json",
  name: "React18 Loaders",
  entryPoints: ["./lib/src"],
  exclude: ["**/*.test.*", "**/index.ts", "**/declaration.d.ts"],
  entryPointStrategy: "Expand",
  out: "./docs",
  commentStyle: "all",
  searchInComments: true,
  excludeExternals: true,
  plugin: [
    "typedoc-plugin-markdown",
    "typedoc-plugin-mdn-links",
    "typedoc-plugin-rename-defaults",
    "typedoc-plugin-missing-exports",
  ],
  hidePageHeader: true,
  sanitizeComments: true,
  router: "module",
  mergeReadme: true,
  hideBreadcrumbs: true,
  expandParameters: true,
  expandObjects: true,
  theme: "markdown",
};
