#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACM | grep -E '\.(ts|tsx|js|json)$' || true)
[ -z "$FILES" ] && exit 0

biome check --write $FILES
pnpx @promptshield/cli --check $FILES

git add $FILES
